import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Hustlrzz",
  description: "The terms that govern your use of the Hustlrzz AI interview coaching platform.",
};

const sections = [
  {
    title: "1. Coaching, not assessment",
    body: [
      "Hustlrzz provides practice and coaching. Scores, reports, presence signals and verdicts are directional training feedback generated by AI models.",
      "Nothing produced here is a hiring decision, a medical or psychological evaluation, or a guarantee of interview outcomes with any employer.",
    ],
  },
  {
    title: "2. Your account",
    body: [
      "You are responsible for the accuracy of the resume, job descriptions, notes, and other material you upload, and for keeping your credentials safe.",
      "We may suspend accounts that abuse the service, attempt to disrupt other users, or exceed reasonable usage of metered features.",
    ],
  },
  {
    title: "3. Your content",
    body: [
      "You keep ownership of everything you upload. You grant us a limited license to process it solely to deliver the features you request (preparation packs, interviews, coaching reports, knowledge search).",
      "Camera video frames never leave your browser. Only text you submit and numeric presence summaries reach our servers.",
    ],
  },
  {
    title: "4. Third-party services",
    body: [
      "Hustlrzz relies on third-party providers for authentication, storage, AI inference, and public web research. Their availability and policies apply to those components.",
      "Public research results carry source links; reported company patterns are likelihoods drawn from public sources, never confirmed internal policy.",
    ],
  },
  {
    title: "5. Availability and changes",
    body: [
      "Features may change as the product evolves. We aim to announce breaking changes but provide the service without an uptime warranty.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-14 md:px-6">
      <Link href="/" className="text-sm font-semibold text-primary">← Back to Hustlrzz</Link>
      <h1 className="mt-4 text-4xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Plain-language terms for using Hustlrzz.</p>
      <div className="mt-10 space-y-8">
        {sections.map((section) => (
          <section key={section.title}>
            <h2 className="text-lg font-semibold">{section.title}</h2>
            {section.body.map((paragraph) => (
              <p key={paragraph.slice(0, 24)} className="mt-3 text-sm leading-7 text-muted-foreground">{paragraph}</p>
            ))}
          </section>
        ))}
      </div>
    </main>
  );
}
